using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OnlineFoodOrderingSystem.Models
{
    // Represents a customer in the online food ordering system
    // This class stores customer information including contact details and address
    public class Customer
    {
        // Primary key for the Customer table
        // Auto-generated by the database
        [Key]
        public int CustomerId { get; set; }

         // Customer's full name
        // Required field with maximum length of 100 characters
        [Required(ErrorMessage = "Customer name is required")]
        [StringLength(100, ErrorMessage = "Name cannot exceed 100 characters")]
        [Display(Name = "Customer Name")]
        public string CustomerName { get; set; }

        // Customer's email address
        // Must be in valid email format
    
        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid email address")]
        [StringLength(100)]
        public string Email { get; set; }

    
        // Customer's contact phone number
        // Required for order delivery coordination
     
        [Required(ErrorMessage = "Phone number is required")]
        [Phone(ErrorMessage = "Invalid phone number")]
        [Display(Name = "Phone Number")]
        [StringLength(15)]
        public string PhoneNumber { get; set; }

    
        // Customer's delivery address
        // Required for food delivery
      
        [Required(ErrorMessage = "Address is required")]
        [StringLength(200, ErrorMessage = "Address cannot exceed 200 characters")]
        public string Address { get; set; }

        // Navigation property for orders placed by this customer
        // One customer can have many orders (One-to-Many relationship)
        
        public virtual ICollection<Order>? Orders { get; set; }
    }
}